### ISSUE TITLE
PPTX document takes too much time to load

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring#17]
Hi,
Please notice a sample presentation has 22 slides and takes about 5min. to load. 
During that time, CPUs are overloaded to 100%, please check the screenshot below.
![2](https://user-images.githubusercontent.com/41449852/49257228-e8bbd980-f431-11e8-9c18-6d8350a89e31.png)
Since the presentation is private, it has been emailed to @egorovpavel 
Best Regards.

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose we are investigating this issue

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose we confirmed the issue and reported to library developers team. Although we still investigating, this issue related to the fact that we load document page by page and in separate threads.

Meanwhile, we will publish workaround to our examples that in case showcase configured to load all pages(setting `preloadPageCount` to `0`) will load all pages in one request instead of page by page.

Let us know if this workaround works for you.

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose we updated our annotation samples with a mentioned workaround, please pull latest changes and let us know if this worked for you.

**Comment by aleksandarvidakovicaspose** [comment]
Hi @egorovpavel 
Thanks for your effort.
However, our customer hasn't found a satisfied difference.
If possible, please share an ETA for the fix or another workaround.

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose we apologize for this delay. This issue has been solved in the .NET version of GroupDocs.Annotation library, now we are waiting for a Java release. At this moment ETA for Java release is the end of next week. We will update you in case there will be any changes in the timeline.

**Comment by aleksandarvidakovicaspose** [comment]
Hi @egorovpavel 
This is great news to hear. Thanks for the notification.

**Comment by egorovpavel** [comment]
Hi, @aleksandarvidakovicaspose
Unfortunately, it is was not possible to include this fix in the upcoming release. Fix for this issue is already in the roadmap for the next release with the highest priority.  Next release is planned to the end of March/first week of April.

**Comment by egorovpavel** [comment]
Hi, @aleksandarvidakovicaspose. We benchmarked the latest version(19.4) of GroupDocs.Annotation library for Java and observed from 3x to 4x increase in performance depending on the file. Let us know if this works for you.
