### ISSUE TITLE
Unable to modify/delete annotation

### ISSUE THREAD

**Issue by samicheemagroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring#19]
This issue was originally raised via forum thread:
https://forum.groupdocs.com/t/how-can-we-modify-delete-already-annotated-documents-in-groupdocs-annotation-jar-18-10-for-java/6827

I am trying to modify/delete annotation from already annotated document. But failed to see the changes in the document on refreshing the browser.

**Comment by egorovpavel** [comment]
@samicheemagroupdocs this issue has been fixed with #20. Please pull the latest changes and rebuild the project.
