### ISSUE TITLE
Unable to download npm packages

### ISSUE THREAD

**Issue by samicheemagroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring#2]
This issue was originally raised via forum thread: https://forum.groupdocs.com/t/while-viewing-files-cpu-utilization-is-more-using-groupdocs-annotation-for-java/6556/10

One of the user is unable to download npm packages even using his personal network. Please find attached log of two different machines shared by him. Is there a workaround?. Thanks

[npm-debug.zip](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring/files/2510526/npm-debug.zip)

**Comment by egorovpavel** [comment]
### First NPM log 

Stacktrace indicates that the user is behind the proxy. As a workaround,  we recommend configuring maven to use a proxy in the pom.xml file. 

[How to configure a proxy for maven](http://maven.apache.org/guides/mini/guide-proxies.html)

### Second NPM log

In the second log, everything looks ok, up to the last line that indicates that there is lack of permissions.

> 67176 error Please try running this command again as root/Administrator.

there might be two possible issues:

- lack of permissions
- some other software like Antivirus or Windows defender prevent files from being renamed


To workaround first, we recommend executing `maven` as administrator

To workaround second issue we suggest temporary disable Antivirus/Windows defender  or add an exclusion for node.exe
