### ISSUE TITLE
After pull the latest changes, annotation icons are all gone

### ISSUE THREAD

**Issue by holyman2k** [groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring#29]
After pull latest git changes, after run mvn clean spring-boot:run, all annotation icons disappeared
![screen shot 2019-01-07 at 9 51 48 am](https://user-images.githubusercontent.com/729313/50742623-0450a600-1262-11e9-9d89-d420557d73b6.png)

**Comment by koleslena** [comment]
This problem was fixed. Please, pull new version.

**Comment by holyman2k** [comment]
Thank you.  Problem is fixed

**Comment by holyman2k** [comment]
Now when i open any document, i get this error in js console:
ReferenceError gd_prefix_page gd-prefix_page is not defined 

annotation.js
line 1558        if (!gd_prefix_page.hasClass('loaded')) {

**Comment by holyman2k** [comment]
Hi, I pull the latest version and the annotation icons are back.Thank you.

Now when i set preloadPageCount:1 in the configuration.yml file. I get the following js error:

![screen shot 2019-01-08 at 10 18 12 am](https://user-images.githubusercontent.com/729313/50799074-c2416600-132e-11e9-804f-b74f117de4c5.png)

**Comment by koleslena** [comment]
The problem was fixed. Please, pull new version again.

**Comment by egorovpavel** [comment]
@holyman2k we consider this issue closed
