### ISSUE TITLE
Multi exceptions raise while deploying the app on Tomcat server

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring#31]
Hi,

Please notice we have difficulties while deploying the app on Tomcat server. We are getting numerous exceptions while running the application using Netbeans. This looks like an issue with the incorrect configuration, but we have tried many plugins without success.
Tomcat server version is 9. 0. 13 and all configuration files are attached(settings.xml, server.xml, tomcat-users.xml). Also, an edited POM.xml file is attached.

Please investigate and advise.

Thanks.
[The stack trace.txt](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring/files/2770675/The.stack.trace.txt)
[config files.zip](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring/files/2770678/config.files.zip)

**Comment by koleslena** [comment]
Hi,
We added possibility building to war for further deployment on an external server. Please, checkout new version.

For building war use 'mvn package -P war', after war is ready, it can be deployed on any servers.

If you want to use maven plugin for deployment, profile war must be specified like this ' -P war' , see example for tomcat plugin in pom.xml. For example, for tomcat7 plugin, uncomment 231-240 lines in pom.xml and use ''mvn -P war tomcat7:deploy' to deploy. For any other plugins it is similar.

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose we will consider this issue as resolved. Feel free to reopen it if still have questions.
