### ISSUE TITLE
Text field annotation disappears in the output document

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring#37]
Using this showcase project when we add text field annotation in a PDF, save and download it. We cannot see text field in the output document.
However, in the output document, if we click on the same location or hover mouse where annotation was added. Then we can see text. 
![text annotation](https://user-images.githubusercontent.com/15940608/52262638-cc1ab100-294e-11e9-9ead-e1b217a2d198.JPG)
And when you double click on the annotation location then the text-field appears, see this screenshot
![double click](https://user-images.githubusercontent.com/15940608/52262750-2f0c4800-294f-11e9-823c-01f69ee64512.JPG)

Can text-field annotation be visible in the output document without clicking or mouse hovering?

**Comment by koleslena** [comment]
Hello!
Please specify some information.
What application do you use to open the annotated file? And what OS do you use? Also can you attach the annotated file for testing?
Thank you!

**Comment by atirtahirgroupdocs** [comment]
Hi,
Sorry, but the issue is resolved at my end. It was related to environment.
