### ISSUE TITLE
Offset when drawing annotations IE11

### ISSUE THREAD

**Issue by MartinKallinger** [groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring#38]
When I Start the application, everything works fine in Chrome and Firefox, but when i want to draw annotations on IE 11 the annotation created on click has an offset to the position I wanted the annoation to be. For me it also seems that placing an annotion on top of the document has less offset then placing an annotation on the bottom half of the document. 

Is there any solution to get the showcase working in IE11? Our customers mostly use this browser.

**Comment by Pavel-Teplitsky** [comment]
@MartinKallinger Thank you for your request. We will check this issue and return to you.

**Comment by Pavel-Teplitsky** [comment]
@MartinKallinger Sorry for the delay, we have fixed the issue, please rebuild your solution to pull latest updates for the front-end. Also you can clean your browser cache to ensure that the browser will load updated version.

Best regards.

**Comment by MartinKallinger** [comment]
@Pavel-Teplitsky  Thank your for your help :-) I will update the project in a second and have a look

**Comment by MartinKallinger** [comment]
@Pavel-Teplitsky  works perfectly thank you
