### ISSUE TITLE
Application is consuming 100% resources usage while loading

### ISSUE THREAD

**Issue by samicheemagroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring#4]
This issue was originally raised via forum thread: https://forum.groupdocs.com/t/while-viewing-files-cpu-utilization-is-more-using-groupdocs-annotation-for-java/6556/14

Hi,

Application is consuming up to 100 % resources usage while loading the source file. Following are the screenshots of CPU consumption while rendering two documents (Slide and Word).  

Slide Document:
![screenshot_slides](https://user-images.githubusercontent.com/29034002/47677381-c0498100-dbe0-11e8-99a3-044996f6b552.png)

Word Document:
![screenshot_words](https://user-images.githubusercontent.com/29034002/47677403-d1928d80-dbe0-11e8-809c-64c60437e9ed.png)

Furthermore, you may also find sample documents [here](https://drive.google.com/drive/u/0/folders/1Bz79UKZWNiSi9wF4bb0w7oydNwns1PNs).

**Comment by egorovpavel** [comment]
@samicheemagroupdocs we just published workaround for #17  that might solve this issue as well. Please let us know if this fix works for you.

**Comment by egorovpavel** [comment]
@samicheemagroupdocs i was not able to reproduce indicated stable 100% CPU load behavior using the latest version and setting in configuration.yml `preloadPageCount=0`Got following results:
<img width="1680" alt="screen shot 2018-12-06 at 12 12 43" src="https://user-images.githubusercontent.com/737110/49583826-387a3380-f951-11e8-8823-0f7ddb52ac9e.png">

Please confirm that you tested using the latest version and set `preloadPageCount=0` in configuration.yml.

Also note, that this is just workaround for #17 and it tries to reduce loading times.
