### ISSUE TITLE
The request for zoom in/zoom out functionality

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring#44]
Hi,

Please notice the customer has asked for Zoom in and Zoom out functionality.
It seems that this feature isn't provided, at this moment.

Please consider the implementation and let me know about the further plans.
Thanks in advance.

**Comment by egorovpavel** [comment]
Hi @aleksandarvidakovicaspose, implementation of this feature is expected to be finished next week.

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose this feature has been released. Please pull the latest version, rebuild project and clean browser cache.
