### ISSUE TITLE
Fit to page functionality

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring#45]
Hi,

Please notice the customer is interested in fit-to-page functionality.
If possible, please implement it and provide an estimate.

Best Regards.

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose, implementation of this feature is expected to be finished next week.

**Comment by egorovpavel** [comment]
@aleksandarvidakovicaspose this feature has been released. Please pull the latest version, rebuild project and clean browser cache.
