### ISSUE TITLE
Set or change font color and size of the annotation 

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring#47]
This issue was originally raised via forum thread: https://forum.groupdocs.com/t/group-docs-annotation-fields-css-issue/7110

Hi,
Can you please add a feature to set **font-size and color** of the annotations such as watermark, text-field.
Currently there is no such option in the front-end. So font-size and color seems rigid.

**Comment by egorovpavel** [comment]
Hi @atirtahirgroupdocs, we will schedule the implementation of this feature for next week. I'll let you know once it released.

**Comment by atirtahirgroupdocs** [comment]
@egorovpavel alright. Thanks for the update.

**Comment by egorovpavel** [comment]
Hi @atirtahirgroupdocs, this feature has been released.
