### ISSUE TITLE
Application deployment issue

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring#48]
This issue was originally raised via forum thread: https://forum.groupdocs.com/t/group-docs-annotation-signature-deployment-issue/7112

Generated war : mvn package -P war
But cannot successfully deploy war on the tomcat server. Please find the exception details in the attached file.
[exception.txt](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring/files/3000260/exception.txt)

However, war is extracted in apache-tomcat-7.0.77\webapps
But getting this exception, cannot deploy and run application.

**Comment by koleslena** [comment]
Hi, what version of java do you use?

**Comment by atirtahirgroupdocs** [comment]
java version "1.8.0_77" 
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**Comment by koleslena** [comment]
Hi, I tested with tomcat 8, the deployment works well. While I investigate the problem with tomcat 7, the customer can use tomcat 8. And, as I see from forum posts, they used the old version of annotation, 1.12.2, the current version is 1.12.15, please try the newest version.

**Comment by atirtahirgroupdocs** [comment]
@koleslena ,

I used latest version of the project at my end with both tomcat 7 & 8. But I am not able to deploy it on server. Please find the exception details attached.
[tomcat exception.txt](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring/files/3013323/tomcat.exception.txt)
User tried latest version on tomcat 9 as well. But there is same exception.

**Comment by koleslena** [comment]
I deployed the app successfully on tomcat 8 and 9. For tomcat 7, our app can not work well, because tomcat 7 has old libs, and spring boot 2 doesn't support them. Can you please attach your war, I can not reproduce error, my war was deployed successfully.

**Comment by atirtahirgroupdocs** [comment]
Please download the war file [here](https://drive.google.com/open?id=1sRafj4QDwUtx2Gjug15BwjzJOi9MqIGk).
Exception details - [exception.txt](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring/files/3016835/exception.txt)

**Comment by koleslena** [comment]
Thank you! Your war was deployed successfully for me too. We found out that this bug reproduces for Windows only, for Unix systems deployment works successfully. We are investigating this problem and will notify you as soon as get something new.

**Comment by atirtahirgroupdocs** [comment]
@koleslena can you please share ETA of fix?

**Comment by koleslena** [comment]
We are expecting new version of groupdocs-annotation in next week, there the problem will be solved

**Comment by atirtahirgroupdocs** [comment]
@koleslena will this issue be resolved in this week?

**Comment by koleslena** [comment]
Hi, sorry, we didn't receive the new version of groupdocs-annotation in this week, so it is totally not in this week. I'll let you know when I get to know deadline for groupdocs-annotation release

**Comment by koleslena** [comment]
we are waiting for new version today, as soon as we get it, we release the fix

**Comment by atirtahirgroupdocs** [comment]
@koleslena alright. Thanks for the update.

**Comment by koleslena** [comment]
@atirtahirgroupdocs the problem has been fixed. Please pull the latest changes.
