### ISSUE TITLE
Resource redaction inconsistency

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring#50]
Hi,

Please notice that DOCX and PDF documents are not annotated in the same manner.
When applying the resource redaction DOCX document, the output annotation isn't transparent.
However, PDF document output has partially (50%) transparent annotation.

Please provide consistent transparency for both (PDF and DOCX) annotations.
All resources can be found below,
[Resource Redaction.docx](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring/files/3031437/Resource.Redaction.docx)
[Resource Redaction.pdf](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring/files/3031438/Resource.Redaction.pdf)
[Resource Redaction_annotated.docx](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring/files/3031439/Resource.Redaction_annotated.docx)
[Resource Redaction_annotated.pdf](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring/files/3031440/Resource.Redaction_annotated.pdf)

Best Regards.

**Comment by koleslena** [comment]
Hi,
We reproduced the bug. Now we are investigating this problem and will notify you as soon as get something new.

**Comment by koleslena** [comment]
We are expecting new version of groupdocs-annotation in next week, there the problem will be solved

**Comment by koleslena** [comment]
@aleksandarvidakovicaspose  the problem has been fixed. Please pull the latest changes.
