### ISSUE TITLE
The text redaction doesn't work properly for DOCX documents.

### ISSUE THREAD

**Issue by aleksandarvidakovicaspose** [groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring#51]
Hi,

Please notice the text redaction is missing in the annotated DOCX output. Besides, it looks that strikeout redaction is also missing.

Please find the source and the output DOCX documents below,
[Source.docx](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring/files/3031541/Source.docx)
[Text Redaction.docx](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring/files/3031542/Text.Redaction.docx)
![text redaction](https://user-images.githubusercontent.com/41449852/55362703-12b60300-54db-11e9-83e1-b33b1dfe4d3c.png)

Best Regards.

**Comment by koleslena** [comment]
Hi, 
We reproduced the bug. Now we are investigating this problem and will notify you as soon as get something new.

**Comment by koleslena** [comment]
Hi,
we are waiting for new version of groupdocs-annotation, as soon as we get it, we release the fix

**Comment by koleslena** [comment]
@aleksandarvidakovicaspose the problem has been fixed. Please pull the latest changes.
