### ISSUE TITLE
Text redaction annotation looks like a black box in exported document.

### ISSUE THREAD

**Issue by BorisPazinAspose** [groupdocs-annotation/GroupDocs.Annotation-for-Java-Spring#7]
Open a file (i.e. [annotationsHello world.pdf](https://drive.google.com/open?id=1MoX14APAAv6Aj6XefaQ6BCVyrsqp6-lY) ), 
Add Text Redaction annotation from left menu, 
Save the file, 
Download annotated file. In output file, annotation looks like a black box. Please check output [annotationsHello world (3).pdf](https://drive.google.com/open?id=1WMIwT0xJNhJdkmyFelkW8-DF699bnDj6)

**Comment by egorovpavel** [comment]
from [documentation](https://docs.groupdocs.com/display/annotationnet/Adding+Text+Redaction+Annotation):

> Text Redaction Annotation helps in blacking out or deleting a text in a document.

or I missing the point?

**Comment by BorisPazinAspose** [comment]
@egorovpavel , you're right, thanks for pointing out. You may close the issue. Thanks.
